### ISSUE TITLE
Improper version parsing

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/to-semver#3]
At the moment, this package uses `semver.valid` in combination with `semver.clean` to process the provided versions. The problem here is that some versions aren't supported directly.

```js
toSemver([" 1.0.0 "])
//=> []

toSemver(["v1"])
//=> []
```

The calls fail because `semver.valid` is called first, which returns null even though only `semver.clean` is able to correctly parse the version in the first example.

Also, both of those calls fail when given a version string like as in the second example. The correct strategy here is to use `semver.valid(semver.coerce(version))` as shown [here](https://github.com/Richienb/clean-semver).

A fix to this issue may require somehow storing the identity of each string in the array, using the true parsing strategy and somehow reverting back to the previous values after sorting unless `clean` has been specified.

cc @sindresorhus

**Comment by sindresorhus** [comment]
I agree with your assessment, but I think it should remove whitespace even when `clean: false`, as the clean option is about the version itself, not the whitespace.

> A fix to this issue may require somehow storing the identity of each string in the array

We could store the original and cleaned version in a `Map`.
